### PR TITLE
Upgrade react to 17

### PR DESCRIPTION
**Pull request by Powersource**
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/342

### CODE REVIEW

**Comment by Powersource** [comment]
As mentioned in the issue I've uninstalled the autoscroll dep used because it didn't support react 17 and it didn't seem to work where we used it in the app. The dev seems to have fixed the incompat now though so we could try re-adding it at some point if we want

https://github.com/brianmcallister/react-auto-scroll/issues/35

**Comment by gustavlrsn** [comment]
The monster dialog is a bit weird without autoscroll so would be good to keep it

**Comment by Powersource** [comment]
Yeah but that's the thing, it's not working at the moment :P I suggest we fix it in another PR but I can do it here if you want

**Comment by gustavlrsn** [comment]
Ah, ok, gotya. Let's fix that in another PR then

**Pull request merged**
